### PR TITLE
Allow newer version of psr/log

### PR DESCRIPTION
**Pull request by shadowhand**
PSR-3 has added strict typing in new versions.

### CODE REVIEW

**Comment by dantleech** [comment]
thanks, need a rebase now

**Comment by shadowhand** [comment]
@dantleech done.

**Comment by dantleech** [comment]
thanks!

**Comment by shadowhand** [comment]
@dantleech you bet!

**Comment by shadowhand** [comment]
@dantleech can we get a new 0.5 release of this package? I'd like to start using it for some class discovery in our project and this PR was a blocker.

**Comment by dantleech** [comment]
Done

**Pull request merged**
