### PR TITLE
make testClassmap verify detection of 2 classes in same file

### PR DESCRIPTION
**Pull request by kermorgant**

### CODE REVIEW

**Comment by dantleech** [comment]
Looks like a test config issue... will try and have a look today

**Comment by dantleech** [comment]
I updated master, could you rebase?

**Comment by kermorgant** [comment]
done

**Comment by dantleech** [comment]
I don't _think_ you rebased -- I pulled and opened a new rebased PR :crossed_fingers:

**Comment by dantleech** [comment]
#11

**Pull request closed without merging**
